# Generated by Django 5.0.4 on 2024-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('opciones', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('danado', 'Dañado')], max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
