# Generated by Django 5.0.4 on 2024-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Título Predeterminado', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad', models.CharField(choices=[('Kg', 'Kg'), ('g', 'g'), ('L', 'L')], default='Kg', max_length=10)),
                ('categoria', models.CharField(choices=[('Vegetales', 'Vegetales'), ('Frutas', 'Frutas'), ('Hierbas', 'Hierbas')], default='Vegetales', max_length=100)),
                ('descripcion', models.TextField(default='Descripción predeterminada')),
            ],
        ),
    ]
