# Generated by Django 5.0.4 on 2024-04-21 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='20240421193527', max_length=20, unique=True)),
                ('titulo', models.CharField(default='Título Predeterminado', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad', models.CharField(choices=[('Kg', 'Kg'), ('g', 'g'), ('L', 'L')], default='Kg', max_length=10)),
                ('categoria', models.CharField(choices=[('Vegetales', 'Vegetales'), ('Frutas', 'Frutas'), ('Hierbas', 'Hierbas')], default='Vegetales', max_length=100)),
                ('fechaCosecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(default='Descripción predeterminada')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_vendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['codigo'],
            },
        ),
    ]
