# Generated by Django 5.0.4 on 2024-04-22 04:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='codigo',
            field=models.CharField(default=core.models.generar_codigo, max_length=20, unique=True),
        ),
    ]
