# Generated by Django 5.0.4 on 2024-04-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_cosecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
