# Generated by Django 5.0.4 on 2024-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('vegetales', 'Vegetales'), ('frutas', 'Frutas'), ('hierbas', 'Hierbas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'g'), ('L', 'L')], max_length=10),
        ),
    ]
