# Generated by Django 5.0.4 on 2024-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_publicacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_cosecha',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='cantidad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
