# Generated by Django 5.0.4 on 2024-04-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
