# Generated by Django 5.0.4 on 2024-04-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
